jaychenblue/scout-concordia

app/src/main/java/com/example/scoutconcordia/MapsActivity.java
Seems that when i open the app the gps brings me to google headquarters but that might be a problem with my gps.
=> Double checking everything works

app/src/main/java/com/example/scoutconcordia/MapsActivity.java
There was a bug that the map was not loading properly. I tried this version on my computer and everything is working fine so i would like to set it as the master.
=> Merge to master

.idea/misc.xml, app/src/main/java/com/example/scoutconcordia/MapsActivity.java, app/src/main/res/layout/activity_maps.xml, app/src/main/res/values/strings.xml
Toggle button and functionality implemented and working.
=> Toggle between campuses

.gitignore, .idea/misc.xml, .idea/workspace.xml, app/src/main/java/com/example/scoutconcordia/MapsActivity.java, app/src/main/res/drawable/ic_search_black_24dp.xml, app/src/main/res/layout/activity_maps.xml
This is part of the #26 
implemented "From" search bar and "To" search bar
Screenshot(SGW)
Screenshot(LOYOLA)
=> Outdoor location 

.gitignore, .idea/misc.xml, .idea/workspace.xml, app/src/main/java/com/example/scoutconcordia/MapsActivity.java, app/src/main/res/drawable/ic_search_black_24dp.xml, app/src/main/res/layout/activity_maps.xml
Reverts jaychenblue/scout-concordia#86
The to/from header was covering the search bar that was implemented. Further investigation will be necessary.
=> Revert "Outdoor location "

app/src/main/java/com/example/scoutconcordia/MapsActivity.java
For issue #89 change was rewritten through merges, this edits it back
=> Reintroduced toggle fix

build.gradle
this is linked to the issue #150
=> Sonar qube set up

app/src/main/res/values/styles.xml
PO requested that the colour of the top bar matches the colour theme of the application.
=> Top bar colour change

app/src/main/res/layout/activity_shuttle_schedule.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
The modifications were made as to enhance legibility of the shuttle bus schedule. 
The colours used were those of the official colour palette. 
Issue related to it: #135
=> Shuttle schedule UI modification

app/build.gradle, app/src/test/java/com/example/scoutconcordia/BuildingInfoTest.java, app/src/test/java/com/example/scoutconcordia/LinkedListTest.java
- JUnit was upgraded to JUnit 5
- Annotations were updated to JUnit 5
This PR will close issue #166.
=> Refactoring JUnit tests

app/build.gradle, app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java, app/src/main/res/color/travel_mode_bar_button_selector.xml, app/src/main/res/layout/outdoor_buildings_diections_ui.xml, app/src/main/res/menu/travel_modes_bar.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
Directions to Concordia buildings from Concordia buildings or user's location. 
- supports 4 modes of travelling (walking, car, bus, and shuttle)
- shuttle mode is only available when starting point and destination point are in different campuses (loyola/SGW)
Shuttle unavailable:
Shuttle available:
=> Outdoor directions to concordia buildings

app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java, app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java
=> [#156] Fixed a bug that prevents the project from running when instantiating the ShuttleInfo class.

app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java, app/src/main/java/com/example/scoutconcordia/DataStructures/LinkedList.java, app/src/main/java/com/example/scoutconcordia/DataStructures/N_aryTree.java, app/src/main/java/com/example/scoutconcordia/FileAccess/DES.java
This PR is related to defects D-7, D-8, D-9, D-10, D-11, D-12
Issues #207, #208, #209, #210, #211, #212
=> Defect fixes detected by SonarQube 

app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java
According to SonarQube, we can fix the bugs by using try-resources or finally blocks. 
However, we are unable to close the files in the finally blocks. @vicmanea and myself have tried.
In order to find out if this is fixes the leak, we must run sonarqube again. However, we can only run in on the master branch.
=> [#213] Refactorting using try-resources.

app/src/main/java/com/example/scoutconcordia/DataStructures/Graph.java, app/src/main/java/com/example/scoutconcordia/DataStructures/LinkedList.java
This PR resolves and closes the following issues:
- D-14 (#221)
- D-15 (#222)
- D-16 (#223)
Acceptance criteria:
=> Defect fixes for D-14, D-15, D-16

app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java, app/src/main/res/layout/activity_maps.xml
This pull request is related to #259 
The is feature is work from building to building and UI as following:
Acceptance criteria are the following:
=> Estimated travel time of different travel mode 

app/src/main/java/com/example/scoutconcordia/DataStructures/LinkedList.java
This PR resolves the following issues:
- D-17 (#243)
- D-18 (#244)
Acceptance criteria:
=> Defect fixes for D-17 and D-18

app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java, app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java, app/src/main/res/layout/activity_maps.xml
[#156] Adding the shuttle route estimate to the main application
=> Adding the shuttle route estimate to the main application

app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java
Adding JavaDoc comments to the ShuttleInfo class, for clarification purposes.
=> [#258] Added JavaDoc comments to the ShuttleInfo class

app/src/main/java/com/example/scoutconcordia/Activities/CalendarActivity.java, app/src/main/java/com/example/scoutconcordia/Activities/MainActivity.java, app/src/main/java/com/example/scoutconcordia/Activities/SettingsActivity.java, app/src/main/java/com/example/scoutconcordia/Activities/SettingsFragment.java, app/src/main/java/com/example/scoutconcordia/Activities/ShuttleScheduleActivity.java, app/src/main/java/com/example/scoutconcordia/Activities/SplashScreenActivity.java, app/src/main/java/com/example/scoutconcordia/FileAccess/DES.java, app/src/main/java/com/example/scoutconcordia/MapInfoClasses/CustomInfoWindow.java, app/src/test/java/com/example/scoutconcordia/BuildingInfoTest.java, app/src/test/java/com/example/scoutconcordia/FileAccessorTest.java, app/src/test/java/com/example/scoutconcordia/GraphTest.java, app/src/test/java/com/example/scoutconcordia/LinkedListTest.java, app/src/test/java/com/example/scoutconcordia/N_aryTreeTest.java
**Summary of changes:**
- The curly bracket code style was applied to all classes
- ShuttleInfo was not changed because it's already being refactored in another branch
- MapsActivity was not changed because it's already being refactored in another branch
<hr />
As stated in the wiki, the team's code style for curly brackets is as follows:
```
public void exampleFunction()
{
if (someBoolean)
{
// do something
}
else
{
// do something else
}
}
```
=> Refactor code style

app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java, app/src/main/java/com/example/scoutconcordia/Directions.java, app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java, app/src/main/res/layout/activity_calendar.xml
This fixes defects 20, 21, 22, 24(#281, #282, #286 , #289 )
Changes were made in Directions.java and ShuttleInfo.java
Things to verify:
-[ ] Are we getting proper estimates when selecting the shuttle bus are mode of transport
(In order to get an estimate, go to line 135 in ShuttleInfo.java and comment out lines 135-137 and add SUNDAY as a case under case line 139. This way you get an estimate, and not just a string that says there's no shuttle on Sudnays.
=> Defect fixes D-20, D-21, D-22, D-24

app/src/main/java/com/example/scoutconcordia/ExternalButtonListener.java, app/src/main/java/com/example/scoutconcordia/MapInfoClasses/ShuttleInfo.java
This pertains to issues #284 and #275 
The goal was to refactor the code in order to reduce the complexity of addExploreInsideButtonListener() method as well as removing duplicated code by replacing literals by constants.
=> Fixing code smells detected by SonarQube

app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java
More Javadoc comments were added to the following classes:
- CalendarActivity
- MapsActivity
<hr />
**_This is the final PR for this project._**
=> Javadoc comments

app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java, app/src/main/java/com/example/scoutconcordia/Activities/SettingsFragment.java, app/src/main/java/com/example/scoutconcordia/Directions.java
The variable which controlled the accessibility settings was deleted during refactoring, simply needed to add it back in order to accessibility settings to register.
=> [#241] Added missing variable that was deleted by mistake during refactoring

app/src/main/java/com/example/scoutconcordia/Activities/MapsActivity.java, app/src/main/java/com/example/scoutconcordia/Activities/SettingsFragment.java, app/src/main/java/com/example/scoutconcordia/Directions.java
This was not ready to merge. The accessibility feature still doesn't work properly.
=> Revert "Fix for the accessibility feature"
